import Link from "next/link";
import { CustomerSearch } from "../../components/CustomerSearch";

const professionals = [["Camila Rocha", "2,3 km", "R$ 75", "Manicure, pedicure e nail art"], ["Juliana Martins", "3,1 km", "R$ 95", "Fibra, gel e spa dos pés"]];
const portfolio = ["https://images.unsplash.com/photo-1604654894610-df63bc536371?auto=format&fit=crop&w=900&q=80", "https://images.unsplash.com/photo-1610992015732-2449b76344bc?auto=format&fit=crop&w=900&q=80", "https://images.unsplash.com/photo-1607779097040-26e80aa78e66?auto=format&fit=crop&w=900&q=80", "https://images.unsplash.com/photo-1600421683741-5880c11b88fa?auto=format&fit=crop&w=900&q=80"];

export default function ClientePage() {
  return <main><Header /><section className="pageHero"><span className="eyebrow">Painel da cliente</span><h1>Agende seu atendimento em casa.</h1><p>Informe o endereço, escolha o serviço e veja profissionais verificadas perto de você com horários disponíveis.</p></section><section className="pageGrid"><CustomerSearch /><div className="stack"><div className="professionalsGrid" id="resultados">{professionals.map(([name, distance, price, bio]) => <article className="professionalCard" key={name}><img src="https://images.unsplash.com/photo-1596462502278-27bfdc403348?auto=format&fit=crop&w=800&q=80" alt="" /><div><div className="cardTitleRow"><strong>{name}</strong><span>Verificada</span></div><p>{bio}. Aceita atendimento em domicílio hoje.</p><div className="metaRow"><span>★ 4,9</span><span>{distance}</span><span>Disponível</span></div><Link href="/login">Solicitar {price}</Link></div></article>)}</div><section className="pageCard"><div className="panelHeader"><strong>Fotos dos trabalhos</strong><Link href="/profissional">Ver portfólio</Link></div><div className="portfolioStrip">{portfolio.map((image) => <img src={image} alt="Trabalho de manicure" key={image} />)}</div></section></div></section></main>;
}

function Header(){return <header className="topbar"><Link className="brand" href="/"><span className="brandMark">ME</span><span><strong>Manicure Expert</strong><small>Sua manicure onde você estiver.</small></span></Link><nav className="navLinks"><Link href="/profissional">Profissional</Link><Link href="/gestao">Gestão</Link></nav><Link className="navAction" href="/login">Entrar</Link></header>}
